apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-fastapi
spec:
  selector:
    matchLabels:
      app: sample-fastapi
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-fastapi
    spec:
      containers:
      - name: sample-fastapi
        image: rodgomes95/sample-fastapi:0.0.2
        ports:
        - containerPort: 8000
